version: '3'
services:
  app:
    restart: always
    build: .
    container_name: 'micasa-edge'
    working_dir: '/usr/src/app'
    privileged: true
    tty: true
    volumes:
      - ./:/usr/src/app
